services:
  - type: web
    name: durtron-sistema
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: durtron-db
          property: connectionString

databases:
  - name: durtron-db
    databaseName: durtron
    user: durtron
    plan: free
